version: '3.9'

services:
  # Configuraci贸n contenedor de MongoDB
  db:
    image: mongo
    container_name: socket-db-prod
    volumes:
      - socket-db-prod-data:/data/db
    restart: always
    ports:
      - '27020:27017'
    logging:
      driver: none
    networks:
      - backend
  # Configuraci贸n contenedor API
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: socket-api:prod
    container_name: socket-api-prod
    environment:
      MONGODB_URI: db
      JWT_SECRET: secret
      CLOUD_NAME: deqnmn50h
      API_KEY: 563721284152585
      API_SECRET: _wyTCD42cCFarVeZSaF7REqLtgU
    # ports:
    #   - '3002:3000'
    networks:
      - backend
  # Configuraci贸n contenedor API 2
  api-two:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: socket-api-two:prod
    container_name: socket-api-two-prod
    environment:
      MONGODB_URI: db
      JWT_SECRET: secret
      CLOUD_NAME: deqnmn50h
      API_KEY: 563721284152585
      API_SECRET: _wyTCD42cCFarVeZSaF7REqLtgU
    # ports:
    #   - '3003:3000'
    networks:
      - backend
  # Configuraci贸n contenedor nginx
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: socket-balancer:prod
    container_name: socket-balancer-prod
    restart: unless-stopped
    ports:
      - 80:80
    networks:
      - backend

volumes:
  socket-db-prod-data:
    name: socket-db-prod-data

networks:
  backend:
    name: socket-application-network-backend
    driver: bridge
