# stage one
FROM node:lts-alpine as builder

WORKDIR /api

COPY package*.json ./
RUN npm install

# stage two
FROM mcr.microsoft.com/playwright:v1.21.0-focal

EXPOSE 3000

WORKDIR /app

COPY . .
COPY --from=builder /api/node_modules /app/node_modules

CMD [ "npm", "run", "dev" ]